[package]
name = "raft-learn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
protobuf = "2.28"
raft = "0.7.0"
regex = "1.8.4"
slog = "2.7.0"
slog-async = "2.7.0"
slog-term = "2.9.0"
